server:
  port: 28080
spring:
  datasource:
    # url: jdbc:h2:mem:test
    url: jdbc:h2:file:./data/test
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect